services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dispute_app
    restart: unless-stopped
    working_dir: /var/www/html
    user: "82:82"
    volumes:
       - ./:/var/www/html
    environment:
      - APP_ENV=production
      - APP_URL=https://dispute.devifyo.cloud
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    entrypoint: >
      sh -c "chown -R 82:82 /var/www/html/storage /var/www/html/bootstrap/cache && 
             chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && 
             php-fpm"
    networks:
      - default
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: dispute_web
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:8002:80"
    networks:
      - web_network
      - default
    depends_on:
      - app

  db:
    image: mariadb:10.6
    container_name: dispute_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - disputer_db_data:/var/lib/mysql
    networks:
      - default

  # --- ADDED THIS SECTION ---
  phpmyadmin:
    image: phpmyadmin
    container_name: dispute_pma
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=https://dispute.devifyo.cloud/dbase/
    ports:
      - "127.0.0.1:8083:80"
    networks:
      - default
    depends_on:
      - db

volumes:
  disputer_db_data:

networks:
  web_network:
    external: true
  default:
    driver: bridge